name: lhagli
description: Application de livraison en Mauritanie - LHAGLI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Internationalisation
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2

  # Gestion d'état
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0

  # Lancer des appels téléphoniques
  url_launcher: ^6.3.0

  # Icônes Material
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true