import 'package:flutter/material.dart';
import '../models/user_model.dart';
import '../models/order_model.dart';
import '../services/firebase_service.dart';
import '../utils/constants.dart';

class OrderProvider extends ChangeNotifier {
  final FirebaseService _firebaseService = FirebaseService();

  UserModel? _currentUser;
  bool _isLoading = false;

  UserModel? get currentUser => _currentUser;
  bool get isLoading => _isLoading;
  bool get isRegistered => _currentUser != null;

  // Register user profile
  void registerUser(String name, String phone) {
    _currentUser = UserModel(name: name, phone: phone);
    notifyListeners();
  }

  // Clear current user
  void logout() {
    _currentUser = null;
    notifyListeners();
  }

  // Calculate price dynamically based on vehicle type and cargo weight
  double calculatePrice(String vehicle, double weight) {
    final baseRate = AppConstants.vehicleBaseRates[vehicle] ?? 0.0;
    return baseRate + (weight * AppConstants.weightRatePerKg);
  }

  // Place a new transport request
  Future<bool> placeOrder({
    required String location,
    required String vehicle,
    required double weight,
  }) async {
    if (_currentUser == null) return false;

    _isLoading = true;
    notifyListeners();

    try {
      final calculatedPrice = calculatePrice(vehicle, weight);
      final newOrder = OrderModel(
        id: '', // Generated by backend/service
        location: location,
        vehicle: vehicle,
        weight: weight,
        price: calculatedPrice,
        userName: _currentUser!.name,
        userPhone: _currentUser!.phone,
        createdAt: DateTime.now(),
      );

      await _firebaseService.saveOrder(newOrder);
      _isLoading = false;
      notifyListeners();
      return true;
    } catch (e) {
      _isLoading = false;
      notifyListeners();
      return false;
    }
  }

  // Stream order list
  Stream<List<OrderModel>> get ordersStream => _firebaseService.getOrdersStream();

  // Delete order
  Future<void> deleteOrder(String id) async {
    try {
      await _firebaseService.deleteOrder(id);
    } catch (_) {
      // Handle error accordingly
    }
  }
}
